name: Deploy Flask to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      id: apply
      working-directory: ./terraform
      run: |
        terraform apply -auto-approve
        echo "ec2_public_ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload app folder to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ steps.apply.outputs.ec2_public_ip }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "app"
        target: "/home/ec2-user"

    - name: SSH into EC2 and run app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ steps.apply.outputs.ec2_public_ip }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo yum update -y
          sudo yum install python3 gcc python3-devel mysql-devel -y
          pip3 install --user flask flask_sqlalchemy mysql-connector-python boto3
          pkill -f app.py || true
          cd /home/ec2-user/app
          nohup python3 app.py > log.txt 2>&1 &
